# Generated by Django 4.1.7 on 2023-06-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('subclass', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_person', models.CharField(max_length=35)),
                ('contact_person_phone', models.CharField(max_length=24)),
                ('school_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('All', 'All')], max_length=10)),
                ('class_count', models.CharField(blank=True, choices=[('0-6', '0-6'), ('7-15', '7-15'), ('Above 15', 'Above 15')], max_length=10, null=True)),
                ('school_colours', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('All', 'All')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('duration_start', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_end', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('orientation', models.CharField(blank=True, max_length=15, null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='school.classs')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Sesssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('duration_start', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_end', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesssion', to='school.school')),
            ],
        ),
        migrations.AddField(
            model_name='classs',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classs', to='school.school'),
        ),
        migrations.AddField(
            model_name='classs',
            name='sesssion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classs', to='school.sesssion'),
        ),
        migrations.AddField(
            model_name='classs',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classs', to='school.term'),
        ),
    ]
