# Generated by Django 4.1.7 on 2023-06-15 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doc', models.BooleanField(default=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_pharm', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
