# Generated by Django 4.1.7 on 2023-06-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('mname', models.CharField(max_length=45)),
                ('sname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=45)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.classs')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.school')),
            ],
        ),
    ]
